# -*- coding: utf-8 -*-
"""Сергеева Марина Проект ИС-13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FX7p5sVSM4ZFI8dHB7lIgmrA9SOnjNcZ
"""

!pip install pyTelegramBotAPI

import telebot
from telebot import types
api_token = "8044798431:AAHP1Ms4_KklMB8Tjgh0egL49UFsSBHQnuE"
bot = telebot.TeleBot(api_token)

@bot.message_handler(commands=["start"])
def hello(message):
  bot.send_message(message.chat.id, "Доброе полудня от гнома Сергеевой Марины из ИС-13")

@bot.message_handler(commands=["help"])
def hellp(message):
  markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
  btn1 = types.KeyboardButton("погода")
  btn2 = types.KeyboardButton("настроение")
  markup.add(btn1, btn2)
  bot.send_message(message.chat.id, "Данный бот повторяет отправленные сообщения и чуть-чуть еще", reply_markup=markup)

@bot.message_handler(content_types=['text'])
def button(message):
  if message.text == "погода":
    bot.send_message(message.chat.id, "ракета бомба питарда")
  elif message.text == "настроение":
    bot.send_message(message.chat.id, "огонь")
  elif message.text == "кто ты воин?" :
      bot.send_message(message.chat.id, "гномик")
  elif message.text == "мой родной город" :
        bot.send_message(message.chat.id, "Ростов")
  elif message.text == "как живётся внизу?как погодка там?" :
    bot.send_message(message.chat.id, "хорошо братишка")
  elif message.text == f"{message.text}":
    bot.send_message(message.chat.id, text=f"{message.text}")


bot.polling(none_stop=True)